In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Уровень 0

Придумайте матрицы, которые обладают следующими свойствами:

a) диагональная, ортогональная, но не единичная(!):

b) верхнетреугольная, ортогональная:

c) нижнетреугольная, ортогональная:

d) матрица, у которой определитель = 1, и все элементы не равны 0:

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],

[1, 3]])

print(m)

# Ответы
a) диагональная, ортогональная, но не единичная(!):

In [19]:
A = np.array([[-1, 0, 0],[0, 1, 0],[0, 0, -1]])
A

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [20]:
A_transp = np.transpose(A)

In [21]:
A_transp

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [22]:
A @ A_transp

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

b) верхнетреугольная и нижнетреугольная, ортогональная

In [89]:
A1 = np.array([[1,  0,  0 ], [0, 1, 0 ], [0, 0, 1]])
A1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [90]:
A1_transp = np.transpose(A1)
A1_transp

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [91]:
A1 @ A1_transp

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

d) матрица, у которой определитель = 1, и все элементы не равны 0:

In [111]:
A2 = np.array([[10,  2], [2, 0.5]])
A2

array([[10. ,  2. ],
       [ 2. ,  0.5]])

In [112]:
print(np.linalg.det(A2))

1.0


In [116]:
m = np.array([[2, 2],

[1, 3]])

print(m)

[[2 2]
 [1 3]]


In [118]:
w, v = np.linalg.eig(m)
for i in range(len(m)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]
